create extension if not exists pg_cron with schema extensions;

create table if not exists public.daily_challenges (
  id bigint generated by default as identity primary key,
  day_number integer not null unique check (day_number between 1 and 7),
  title text not null default '',
  objective text not null default '',
  description text not null default '',
  temptation_text text not null default '',
  temptation_value numeric not null default 0 check (temptation_value >= 0),
  updated_at timestamptz not null default now()
);

create or replace function public.set_daily_challenge_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists daily_challenges_updated_at on public.daily_challenges;
create trigger daily_challenges_updated_at
before update on public.daily_challenges
for each row execute function public.set_daily_challenge_updated_at();

alter table public.daily_challenges enable row level security;

drop policy if exists "daily_challenges_read" on public.daily_challenges;
create policy "daily_challenges_read"
on public.daily_challenges for select
to anon, authenticated
using (true);

drop policy if exists "daily_challenges_insert" on public.daily_challenges;
create policy "daily_challenges_insert"
on public.daily_challenges for insert
to anon, authenticated
with check (day_number between 1 and 7);

drop policy if exists "daily_challenges_update" on public.daily_challenges;
create policy "daily_challenges_update"
on public.daily_challenges for update
to anon, authenticated
using (true)
with check (day_number between 1 and 7);

grant select, insert, update on public.daily_challenges to anon, authenticated;
grant usage, select on sequence public.daily_challenges_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'daily_challenges'
  ) then
    alter publication supabase_realtime add table public.daily_challenges;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'game_state'
  ) then
    alter publication supabase_realtime add table public.game_state;
  end if;
end;
$$;

create or replace function public.advance_hot_money_day()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if extract(hour from timezone('Europe/Rome', now())) = 6 then
    update public.game_state
    set current_day = least(current_day + 1, 7),
        updated_at = now()
    where id = 1
      and current_day < 7;
  end if;
end;
$$;

select cron.schedule(
  'hot-money-daily-advance',
  '0 * * * *',
  'select public.advance_hot_money_day();'
);
