create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('director', 'contestant')),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_push_subscription_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_updated_at on public.push_subscriptions;
create trigger push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.set_push_subscription_updated_at();

alter table public.push_subscriptions enable row level security;

drop policy if exists "push_subscriptions_server_only" on public.push_subscriptions;
create policy "push_subscriptions_server_only"
on public.push_subscriptions
for all
to service_role
using (true)
with check (true);

grant select, insert, update, delete on public.push_subscriptions to service_role;
grant usage, select on sequence public.push_subscriptions_id_seq to service_role;
