create table if not exists public.prize_transactions (
  id bigint generated by default as identity primary key,
  day_number integer not null check (day_number between 1 and 7),
  reason text not null,
  amount numeric not null,
  balance_before numeric not null check (balance_before >= 0),
  balance_after numeric not null check (balance_after >= 0),
  source_type text not null,
  source_id text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists prize_transactions_day_created_idx
on public.prize_transactions(day_number, created_at desc);

alter table public.prize_transactions enable row level security;
revoke all on public.prize_transactions from anon, authenticated;
grant select, insert on public.prize_transactions to service_role;
grant usage, select on sequence public.prize_transactions_id_seq to service_role;
